name: Ci Api Deploy
on: 
  push:
    branches:
       [master]

jobs:
  Ci api:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install .net core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 9.x

    - name: Restore and Build
      run: |
        dotnet restore
        dotnet build