name: CI CD Api Deploy
on: 
  push:
    branches:
       [master]

jobs:
  CI-CD-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install .net core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x

      - name: Restore and Build
        run: |
          dotnet restore  Dicta-Sanctorum.APi.csproj
          dotnet build Dicta-Sanctorum.APi.csproj
        working-directory: Dicta-Sanctorum.APi
      
      - name: Test
        run: dotnet test Dicta-Sanctorum.API.Tests.csproj ${{secrets.TEST_PARAMS}}
        working-directory: Dicta-Sanctorum.API.Tests

      - name: Publish
        run: dotnet publish Dicta-Sanctorum.APi.csproj -c Release -o ./publish -r linux-arm64 --self-contained true
        working-directory: Dicta-Sanctorum.APi
      
      - name: Deploy
        